[patch.crates-io]
slint = { git = "https://github.com/sandreas/slint.git", branch="reapply-color-fix"} # use for local git (see cargo.toml)
slint-build = { git = "https://github.com/sandreas/slint.git", branch="reapply-color-fix" } # use for local git (see cargo.toml)
i-slint-core = { git = "https://github.com/sandreas/slint.git", branch="reapply-color-fix" } # use for local git (see cargo.toml)
