// SlintCallbacks
import { SlintAudioPlayer, SlintMediaSource, SlintIcons, SlintNavigation, SlintPreferences, SlintStatus, SlintBatteryStatus } from "globals.slint";

export { SlintAudioPlayer, SlintMediaSource, SlintNavigation, SlintPreferences, SlintStatus, SlintBatteryStatus }

import {
    Button,
    HorizontalBox,
    ListView,
    Palette,
    ScrollView,
    Slider,
    Switch,
    VerticalBox,
} from "std-widgets.slint";
import { Navigator } from "navigator.slint";

import { Home } from "home.slint";
import { Audiobooks } from "main/audiobooks.slint";
import { Music } from "main/music.slint";
import { Search } from "main/search.slint";
import { Settings } from "main/settings.slint";
import { Details } from "main/details.slint";
import { Loading } from "_components/Loading.slint";

export component MainWindow inherits Window {
    default-font-family: "Lato";
    default-font-size: 16pt;

    width: 368px;
    height: 552px;

    init => {
        Palette.color-scheme = SlintPreferences.color-scheme;
    }


    SwipeGestureHandler {
        x: 0;
        y: 0;
        width:root.width;
        height:root.height;
        handle-swipe-right: SlintPreferences.enable-gestures;
        handle-swipe-left: SlintPreferences.enable-gestures;
        handle-swipe-down: SlintPreferences.enable-gestures;
        handle-swipe-up: SlintPreferences.enable-gestures;
        swiped => {
            let xdiff = self.current-position.x - self.pressed-position.x;
            let ydiff = self.current-position.y - self.pressed-position.y;
            let is-horizontal-swipe = xdiff*xdiff > ydiff * ydiff;

            if (is-horizontal-swipe) {
                if (self.current-position.x > self.pressed-position.x) {
                    // debug("swipe: back");
                    SlintNavigation.offset(-1);
                } else if (self.current-position.x < self.pressed-position.x) {
                    // debug("swipe: forward");
                    SlintNavigation.offset(1);
                }
            } else if(!is-horizontal-swipe) {
                if (self.current-position.y > self.pressed-position.y) {
                    // debug("swipe: down");
                    SlintNavigation.path(["settings"]);
                } else if (self.current-position.y < self.pressed-position.y) {
                    // debug("swipe: up");
                    let item-id = SlintAudioPlayer.current-item.id;
                    if (item-id != "") {
                        SlintNavigation.path(["details", item-id]);
                    }
                }
            }


        }

        VerticalBox {
            padding:0px;



            Flickable {
                VerticalLayout {
                    if SlintNavigation.route[0] == "home": Home { }
                    if SlintNavigation.route[0] == "audiobooks": Audiobooks { }
                    if SlintNavigation.route[0] == "music": Music { }
                    if SlintNavigation.route[0] == "settings": Settings { }
                    if SlintNavigation.route[0] == "search": Search { }
                    if SlintNavigation.route[0] == "details": Details {
                        item-id: SlintNavigation.route[1];
                    }
                }
            }

        }
    }
}
